# Generated by Django 4.1.7 on 2023-03-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
